services:
  postgres:
    image: postgres:16
    container_name: uber_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: uber_dw
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - "./complete queries of uber.sql:/docker-entrypoint-initdb.d/01_init.sql"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d uber_dw"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-postgres:
    image: postgres:16
    container_name: airflow_metadata_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5434:5432"
    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-init:
    build: .
    container_name: uber_airflow_init
    depends_on:
      airflow-postgres:
        condition: service_healthy
      postgres:
        condition: service_healthy
    env_file:
      - .env.docker
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__WEBSERVER__SECRET_KEY: vaidehi_uber_project_secret
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./:/opt/airflow/project
    command: >
      bash -c "airflow db migrate &&
      airflow users create
      --username admin
      --firstname Vaidehi
      --lastname Doke
      --role Admin
      --email admin@example.com
      --password admin || true"

  airflow-webserver:
    build: .
    container_name: uber_airflow_webserver
    depends_on:
      airflow-postgres:
        condition: service_healthy
      postgres:
        condition: service_healthy
    env_file:
      - .env.docker
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__WEBSERVER__SECRET_KEY: vaidehi_uber_project_secret
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./:/opt/airflow/project
    command: webserver

  airflow-scheduler:
    build: .
    container_name: uber_airflow_scheduler
    depends_on:
      airflow-postgres:
        condition: service_healthy
      postgres:
        condition: service_healthy
    env_file:
      - .env.docker
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__WEBSERVER__SECRET_KEY: vaidehi_uber_project_secret
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./:/opt/airflow/project
    command: scheduler

volumes:
  postgres_data:
  airflow_postgres_data: